### ISSUE TITLE
Adres notyfikacji

### ISSUE THREAD

**Issue by orzeszki** [SoftifyDev/SyliusImojePlugin#1]
Cześć,
chciałbym zapytać czy wtyczka obsługuje adres do notyfikacji, bo próbuję to namierzyć, ale chyba tego nie ma. W obecnej chwili jeśli klient zamknie zakładkę w przeglądarce z okienkiem płatności tuż po realizacji płatności i nie kliknie przycisku "Wróć do sklepu" to sklep nie dostaje notyfikacji o statusie transakcji. 

Czy jest możliwość by to doprogramować?

**Comment by kryslin** [comment]
Tak obsługuje. Zobacz router o nazwie `imoje_notify_do_unsafe`

**Comment by orzeszki** [comment]
Dziękuję za odpowiedź. Czy to wystarczająco bezpieczna implementacja? Według dokumentacji trzeba weryfikować podpis notyfikacji przez nagłówek ```X-Imoje-Signature``` i dopiero wtedy zaktualizować status transakcji. Oczywiście niczego nie wytykam, tym bardziej, że wtyczka jest dostępna dla wszystkich, ale chciałbym żeby to było bezpieczne tak jak wskazuje dokumentacja. 

Teraz coś zobaczyłem. Czy tu chodzi o to, że weryfikacja odbywa się na podstawie puli adresów IP, którymi najpewniej dysponuje tylko iMoje?

**Comment by kryslin** [comment]
Są sprawdzane adresy jak również ten header. Proszę sprawdzić funkcję supports w akcji NotifyAction.php

**Comment by orzeszki** [comment]
Faktycznie... Przepraszam za zamieszanie. Dziękuję bardzo za tak szybki odzew. Wcześniej szukałem po headerze ```X-Imoje-Signature``` ale vscode mi nie złapał tego.

Gratuluję tak udanego pluginu. Bardzo podoba mi się jego budowa :) W takim razie wątek zamykam. Jeszcze raz dziękuję.
